server.port=9090

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=example-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EXAMPLE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/example/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
